---
- job_name: docker
  # use docker.sock to filter containers
  docker_sd_configs:
    - host: "unix:///var/run/docker.sock"
      refresh_interval: 15s
  # use container name to create a loki label
  relabel_configs:
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container'
#- job_name: journal
#  journal:
#    json: false
#    max_age: 12h
#    labels:
#      job: systemd-journal
#    path: "${JOURNAL_PATH}"
#  relabel_configs:
#    - source_labels:
#        - __journal__systemd_unit
#      target_label: unit
#    - source_labels:
#        - __journal__hostname
#      target_label: nodename
#    - source_labels:
#        - __journal_syslog_identifier
#      target_label: syslog_identifier
#    - source_labels:
#        - __journal_container_name
#      target_label: container_name
#  pipeline_stages:
#    - match:
#        selector: '{container_name=~"homeassistant|hassio_supervisor"}'
#        stages:
#          - multiline:
#              firstline: '^\x{001b}'
